### PR TITLE
First pass at IFormFile support

### PR DESCRIPTION
**Pull request by dionfoster**
This is a first pass at adding IFormFile support.  There's a couple of bits I might need help with:
* Should the API accept streams 
* Support for a collection of files
* Should we split the form from the file method
* Wasn't too sure about the mime type and header as there are a couple of ways to do that, guidance on the correct namespace would be appreciated

I'll also probably double back on adding stream tests to ensure the file can be read.

This might also solve https://github.com/JasperFx/alba/issues/70.

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@dionfoster Sorry for the delay. I wouldn't worry about dealing with `StubHttpContext` unless you just want that functionality. Alba as of 3.0 no longer uses that class in the `Scenario()` tests.

For pure form submissions, I think the extension method to take in a Dictionary, then have that written to the HttpRequest.Stream is fine. You could add an optional argument for the actual mimetype, but use a default otherwise.

I don't have an informed opinion on uploading files, sorry.

**Comment by tjeerdhans** [comment]
I adapted @dionfoster's code to the following `HttpContext` extension method:
```cs
public static class HttpContextExtensions
    {
        /// <summary>
        /// Write multi-part form data to the Request Body of the supplied HttpContext.
        /// </summary>
        /// <param name="context">The HttpContext.</param>
        /// <param name="values">Dictionary containing name-value pairs.</param>
        /// <param name="name">Name of the file to attach.</param>
        /// <param name="filePath">Path of the file to attach.</param>
        public static void WriteMultipartFormData(this HttpContext context, Dictionary<string, string> values,
            string name, string filePath)
        {
            WriteMultipartFormData(context, values, new Dictionary<string, string> { { name, filePath } });
        }

        /// <summary>
        /// Write multi-part form data to the Request Body of the supplied HttpContext.
        /// </summary>
        /// <param name="context">The HttpContext.</param>
        /// <param name="values">Dictionary containing name-value pairs.</param>
        /// <param name="files">Dictionary containing name-filepath pairs.</param>
        public static void WriteMultipartFormData(this HttpContext context, Dictionary<string, string> values,
            Dictionary<string, string> files)
        {
            var formDataBoundary = $"----------{Guid.NewGuid():N}";
            var contentType = "multipart/form-data; boundary=" + formDataBoundary;
            context.Request.ContentType = contentType;

            using var multipartContent = new MultipartFormDataContent(formDataBoundary);
            
            // Add values
            if (values != null)
            {
                foreach (var (key, value) in values)
                {
                    multipartContent.Add(new StringContent(value), key);
                }
            }

            // Add files
            foreach (var (name, filePath) in files)
            {
                new FileExtensionContentTypeProvider().TryGetContentType(filePath, out var fileContentType);
                var fileInfo = new FileInfo(filePath);
                using var fileStream = File.OpenRead(filePath);
                var fileContent = new ByteArrayContent(File.ReadAllBytes(filePath));
                fileContent.Headers.ContentType = new MediaTypeHeaderValue(fileContentType);
                fileContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data")
                {
                    FileName = fileInfo.Name,
                    Name = name
                };

                multipartContent.Add(fileContent, fileInfo.Name, name);
            }

            // Fill request body and set content length
            multipartContent.CopyToAsync(context.Request.Body).Wait();
            context.Request.ContentLength = context.Request.Body.Length;
        }
    }
```

I've used this successfully  in the following example:
```cs
 await Application.AlbaHost.Scenario(s =>
    {
        s.ConfigureHttpContext(context =>
        {
            context.HttpMethod("POST");
            context.RelativeUrl("/ilovefiles");
            context.WriteMultipartFormData(null, "formFile", "excellentfiles/file1.zip");
        });

        s.StatusCodeShouldBeOk();
        s.ContentShouldBe("Excellent file, thank you!");
    });
```

**Comment by dionfoster** [comment]
I'm going to close this, as it would make sense to apply this to the new alba internals.  If I get time I might open a new PR.

**Comment by rochitsen** [comment]
@dionfoster was this ever implemented in master branch? The file upload with existing `context.WriteFormData` does not work.

**Pull request closed without merging**
