### PR TITLE
resolving a long list of security vln found using snyk 👍 

### PR DESCRIPTION
**Pull request by LucaPaterlini**

### CODE REVIEW

**Comment by Hawxy** [comment]
Worth mentioning there's no actual security vulnerabilities to be found here, given this is a testing framework to be run in test projects. Typically, you exclude your test & build projects from Snyk as it creates a ton of unnecessary noise. 

The code change is also unnecessary, as the implementation is all in-memory and doesn't send data over a network or between untrusted systems. I'll begrudgingly merge this in given this change is removed.

**Comment by LucaPaterlini** [comment]
Thanks @Hawxy for your reply, reverted the specific commit you mentioned.

**Comment by Hawxy** [comment]
I've rolled the relevant updates for the main package + docs into other PRs, so this can be closed. Thanks for the contribution.

**Comment by LucaPaterlini** [comment]
Hi @Hawxy thanks for your reply and work.
Just runned the scan again and it seems a few of the changes have slipped ...
Can I send a new pr with the leftovers? :)

**Comment by Hawxy** [comment]
The remaining projects are build infrastructure/test projects and don't need to be fixed.

**Pull request closed without merging**
